import { countriesResolver } from "./resolvers";
import {
  Country,
  Iso3166Status,
  Region,
  CountryNameType,
} from "./src/generated/graphql";

describe("resolvers", () => {
  it("returns basic data for a country", () => {
    const country = {
      name: {
        common: "Barbados",
        official: "Barbados",
        native: { eng: { official: "Barbados", common: "Barbados" } },
      },
      tld: [".bb"],
      cca2: "BB",
      ccn3: "052",
      cca3: "BRB",
      cioc: "BAR",
      independent: true,
      status: "officially-assigned",
      currencies: { BBD: { name: "Barbadian dollar", symbol: "$" } },
      idd: { root: "+1", suffixes: ["246"] },
      capital: ["Bridgetown"],
      altSpellings: ["BB"],
      region: "Americas",
      subregion: "Caribbean",
      languages: { eng: "English" },
      translations: {
        ces: { official: "Barbados", common: "Barbados" },
        cym: { official: "Barbados", common: "Barbados" },
        deu: { official: "Barbados", common: "Barbados" },
        est: { official: "Barbados", common: "Barbados" },
        fin: { official: "Barbados", common: "Barbados" },
        fra: { official: "Barbade", common: "Barbade" },
        hrv: { official: "Barbados", common: "Barbados" },
        hun: { official: "Barbados", common: "Barbados" },
        ita: { official: "Barbados", common: "Barbados" },
        jpn: { official: "バルバドス", common: "バルバドス" },
        kor: { official: "바베이도스", common: "바베이도스" },
        nld: { official: "Barbados", common: "Barbados" },
        per: { official: "باربادوس", common: "باربادوس" },
        pol: { official: "Barbados", common: "Barbados" },
        por: { official: "Barbados", common: "Barbados" },
        rus: { official: "Барбадос", common: "Барбадос" },
        slk: { official: "Barbados", common: "Barbados" },
        spa: { official: "Barbados", common: "Barbados" },
        urd: { official: "بارباڈوس", common: "بارباڈوس" },
        zho: { official: "巴巴多斯", common: "巴巴多斯" },
      },
      latlng: [13.16666666, -59.53333333],
      landlocked: false,
      borders: [],
      area: 430,
      flag: "🇧🇧",
      demonyms: {
        eng: { f: "Barbadian", m: "Barbadian" },
        fra: { f: "Barbadienne", m: "Barbadien" },
      },
      callingCodes: ["+1246"],
    };

    const expected: Country = {
      name: "Barbados",
      officialName: "Barbados",
      names: [
        {
          code: "eng",
          official: "Barbados",
          common: "Barbados",
          type: CountryNameType.Native,
        },
        {
          code: "ces",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "cym",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "deu",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "est",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "fin",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "fra",
          type: CountryNameType.Translated,
          official: "Barbade",
          common: "Barbade",
        },
        {
          code: "hrv",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "hun",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "ita",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "jpn",
          type: CountryNameType.Translated,
          official: "バルバドス",
          common: "バルバドス",
        },
        {
          code: "kor",
          type: CountryNameType.Translated,
          official: "바베이도스",
          common: "바베이도스",
        },
        {
          code: "nld",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "per",
          type: CountryNameType.Translated,
          official: "باربادوس",
          common: "باربادوس",
        },
        {
          code: "pol",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "por",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "rus",
          type: CountryNameType.Translated,
          official: "Барбадос",
          common: "Барбадос",
        },
        {
          code: "slk",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "spa",
          type: CountryNameType.Translated,
          official: "Barbados",
          common: "Barbados",
        },
        {
          code: "urd",
          type: CountryNameType.Translated,
          official: "بارباڈوس",
          common: "بارباڈوس",
        },
        {
          code: "zho",
          type: CountryNameType.Translated,
          official: "巴巴多斯",
          common: "巴巴多斯",
        },
      ],
      currencies: [{ code: "BBD", name: "Barbadian dollar", symbol: "$" }],
      tld: [".bb"],
      cca2: "BB",
      ccn3: "052",
      cca3: "BRB",
      cioc: "BAR",
      independent: true,
      status: Iso3166Status.OfficiallyAssigned,
      capitalCities: ["Bridgetown"],
      altSpellings: ["BB"],
      region: Region.Americas,
      subregion: "Caribbean",

      emoji: "🇧🇧",
    };

    const result = countriesResolver([country])()[0];
    expect(result).toEqual(expected);
  });
});
