name: Main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 12.x

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Tests
        run: yarn test
